### ISSUE TITLE
Face detection example

### ISSUE THREAD

**Issue by beckmx** [UT2UH/MaixAmigo#1]
Are there any examples for face detection using the library?

**Comment by UT2UH** [comment]
Sorry, I have not seen any project with face detection/recognition under Maixduino (K210 Arduino) core. Most of ML projects for K210 hardware are done with MaixPy(thon)... There are neither support from the vendor nor interest in the community for Arduino platform for K210. The best starting point to look at what is available is to translate in Chrome [fukuebiz blog on the topics](https://qiita.com/fukuebiz).

**Comment by beckmx** [comment]
I see, well I wanted to give a spin to the library anyway, looks like there is an issue here:

```
Arduino/libraries/MaixAmigo/src/utility/TFT_eSPI_K210.h:63:22: error: 'TFT_CS' was not declared in this scope
   fpioa_set_function(TFT_CS, (fpioa_function_t)(FUNC_SPI0_SS0 + SS_PIN));
                      ^~~~~~
```

**Comment by UT2UH** [comment]
Sorry, it is not mentioned in readme, but to run this library you also need [my fork of Maixduino](https://github.com/sipeed/Maixduino/pull/99) with pin tweaks for all Maix devices.

**Comment by beckmx** [comment]
I managed to get it compiled, just a couple of doubts, the screen looks like it is mirrored, the text is read in the opposite direction, and the touch screen examples with gestures maybe are outdated, I can detect the touch with this:
`if ( MA.Touch.changed ) MA.Lcd.println( MA.Touch.point[0] );`

But the gestures dont run for me

**Comment by UT2UH** [comment]
Even the same looking TFT can have different controller connection to the matrix or even matrix itself. Please check #define MAIX_AMIGO in Config.h and try to play with default rotation for your device.  Lcd.setRotation() should work as well.
